### ISSUE TITLE
[geometry] DOMMatrix stringifier behavior doesn't seem to match implementations

### ISSUE THREAD

**Issue by bzbarsky** [w3c/fxtf-drafts#120]
The spec says to just append the values of the (double) attributes to the string.  But implementations seem to be appending as floats or something; they are certainly appending a much lower precision than a double would give.

**Comment by foolip** [comment]
@cabanier, any ideas for how to align spec with Blink and other implementations?

**Comment by gogag1** [comment]
I'd like to change Blink following the spec.
Link: https://codereview.chromium.org/2846523002/

**Comment by zcorpan** [comment]
The patch has this change to a test
```diff
-  assert_equals(matrix2d.toString(), "matrix(1, 2, 3, 3.1, 2, 1)");
+  assert_equals(matrix2d.toString(), "matrix(1.000000, 2.000000, 3.000000, 3.100000, 2.000000, 1.000000)");
```

It is not clear to me that this is a desirable result.

https://html.spec.whatwg.org/multipage/infrastructure.html#best-representation-of-the-number-as-a-floating-point-number uses JS's `ToString`, which doesn't produce trailing zeros. But can still represent double precision, right?

Related is how to serialize non-finite values. `NaN` and `Infinity` are invalid CSS keywords, so it wouldn't successfully parse again...

**Comment by zcorpan** [comment]
There's also https://drafts.csswg.org/cssom/#serialize-a-css-component-value :

> &lt;number>
A base-ten number using digits 0-9 (U+0030 to U+0039) in the shortest form possible, using "." to separate decimals (if any), rounding the value if necessary to not produce more than 6 decimals, preceded by "-" (U+002D) if it is negative.
Note: scientific notation is not used.

**Comment by gogag1** [comment]
Could I use String::NumberToStringECMAScript(double number) function?
I think it can represent double precision and serialize non-finite values.
Could you review my code?
https://codereview.chromium.org/2846523002/

Thanks.

**Comment by zcorpan** [comment]
I think using JS `ToString` is reasonable here, notwithstanding that non-finite values fail to roundtrip (that is already the case in Chromium and Gecko anyway). Adding Agenda+ (and emailed w3c-css-wg) to discuss this on the CSSWG telecon tomorrow.

**Comment by zcorpan** [comment]
Spec PR: https://github.com/w3c/fxtf-drafts/pull/148

(I'll try to work on tests tomorrow.)

**Comment by AmeliaBR** [comment]
Since it came up in the discussion, one practical case where a DOMMatrix would have infinite values is `skewX(90deg)` or `skewY(90deg)`.  That's a non-invertable operation, and in the `transform` property it causes the element to not be drawn (similar to `scale(0)`).  But it is still a valid transform function, and could reasonably occur as a start or end point in an animation.

Note: I just tested, and neither Chrome nor Firefox currently actually use `Infinity` in the matrix `new DOMMatrix().skewX(90)`, instead they use `1.63312e+16`.   But _if_ the trigonometric functions were mathematically precise, it would be `Infinity`.  (The `c` component of the `skewX(90)` matrix is equal to `Math.tan(Math.PI/2)`.)

The other cases where you you'd get non-finite values in a matrix are where you tried to invert a non-invertable matrix (like `scale(1,0)`): [as currently spec'd](https://drafts.fxtf.org/geometry/#dom-dommatrix-invertself), this does not throw an error, but instead sets all values in the matrix to `NaN`.  (In contrast [SVG 1.1](https://www.w3.org/TR/SVG11/coords.html#__svg__SVGMatrix__inverse) threw an error when trying to invert a non-invertable matrix.)  And of course, the author could be setting individual matrix or transform parameters using calculations that return `Infinity` (1/0) or `NaN` (0/0).  

You wouldn't expect these matrices to have CSS-parse-able equivalents, though.  Skews are a special case because the non-finite matrix representation has a finite transform-function representation.

**Comment by AmeliaBR** [comment]
Also, so it doesn't get forgotten: The main substance of this issue still needs to be resolved.  

When you stringify a matrix to CSS notation, do you follow the "6-decimals & no scientific notation rule" from CSSOM, or do you maintain full double precision, or what?  Currently, Firefox and Chrome seem to use 6-digit precision (which isn't the same as 6-decimals) with scientific notation:

```js
m = new DOMMatrix();
m.a = 1/3;
m.b = 1/300000;
m.c = 100000 + (1/3);
m.d = Number.MAX_SAFE_INTEGER;
"" + m;
// Chrome 58 & Firefox 54 both return: 
// "matrix(0.333333, 3.33333e-06, 100000, 9.0072e+15, 0, 0)"
```

**Comment by zcorpan** [comment]
@AmeliaBR thanks for the examples for Infinity and NaN!

I missed to bring up on the call the precision issue. In #148 I defined it in terms of JS's `ToString`, so that means something like this:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5149

It seems in Safari TP for `WebKitCSSMatrix`, it uses 6 digits and no sci-not:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5150

None of the current browser implementations match CSSOM's serialization rule for numbers.

I think JS `ToString` is reasonable because it makes it *possible* to preserve precision in a roundtrip, if the CSS parser supports parsing into a `double` value for `DOMMatrix`/'transform' etc.
