### ISSUE TITLE
Luminance masking is slower than alpha masking

### ISSUE THREAD

**Issue by jrmuizel** [w3c/fxtf-drafts#137]
The css masking spec adds support for luminance masking of html content and potentially requires browsers to support luminance masking in the compositing path. Does luminance masking have enough advantages to justify the additional implementation burden that this adds?

**Comment by birtles** [comment]
I don't have an opinion about its usefulness except to mention that it was added for compatibility with SVG where luminance is the default. In terms of compatibility, at the very least, when the `mask` property is applied to an SVG element and refers to an SVG `<mask>`, it needs to use luminance. Beyond that we'd probably have to measure how much content uses this to determine if it can be changed.

(As for why SVG has that behavior, I can only guess that it was based on what authoring tools such as Photoshop do?)

**Comment by AmeliaBR** [comment]
The main benefit of luminance masking is that you can use mask images without an alpha channel, such as a JPEG.

**Comment by mstange** [comment]
When @jrmuizel and I talked about this yesterday, our conclusion was that Firefox is the only browser that is currently shipping the ability to do luminance masking on HTML content. Can somebody confirm that conclusion?

cc @cjku

**Comment by jrmuizel** [comment]
@AmeliaBR what's a use case for masking to a JPEG image? i.e. why would I choose to mask to a JPEG instead of a PNG?

**Comment by AmeliaBR** [comment]
@jrmuizel The use case for JPEG is that it is usually a smaller file size for representing photographic image, and it has better browser support than similar formats with alpha channels.

Also, you may be re-using images that you're using elsewhere in the design.  Being able to use the luminance mask can in some cases remove the need to create dedicated image assets for the mask.  This will be even more true when the `filter(<image>)` function is supported, so you can adjust contrast/brightness dynamically in the browser.

For @mstange's question: Last I checked Firefox was the only one that has shipped mask-image un-prefixed. `-webkit-mask-image` doesn't include luminance masking.

**Comment by dirkschulze** [comment]
@jrmuizel In the illustration/design/art space luminance masking is the default masking.  No matter if you use Adobe products like Adobe Photoshop, Adobe Illustrator or Serif products like Affinity Phot.

**Comment by thebabydino** [comment]
I have found the `alpha` mode (the only one supported by WebKit browsers at this point) to be a real PITA when using CSS gradients for masking. With luminance masks, you can have gradient layers one on top of the other in order to get more complex mask shapes that way. With alpha masks you cannot do that. You need to split your whole somewhat more complex mask shape into tiles, size and position your tiles with `mask-size` and `mask-position`, only to find that you end up with thin gaps in between your tiles due to rounding errors.

Yes, I can of course tweak the `mask-size`, make all tiles `1px` larger, but that just feels dirty.

Yes, of course, I can switch to an all SVG solution, have luminance masks by default, but the whole idea was to avoid all that markup.

**Comment by jrmuizel** [comment]
@thebabydino can you provide an example of the kind of thing that you mean? I'm having trouble visualizing it.

@dirkschulze didn't know that. How are those tools handling the lack of luminance masking in browsers other than Firefox today?

**Comment by AmeliaBR** [comment]
@thebabydino I don't think `mask-mode: luminance` will help in the way you are thinking, but `mask-composite` should.

@jrmuizel 
In SVG masking, all the shapes inside the `<mask>` are composited together using normal painting operations, before converting to a mask.  That means that you can add a black shape on top of a white shape to create a donut effect (among many possibilities).  You obviously couldn't do that with a transparent shape on top of an opaque shape.  

But with `mask-composite` and mask layers, you would use two solid shapes (images or CSS gradient layers) and a subtract or exclude composite mode.  Of course, in order to support `mask-composite`, all mask layers are converted to alpha masks before compositing, so there is no difference between luminance and alpha mask layers as far as what types of compositing are possible with multiple mask-image layers.

So once `mask-composite` is fully supported, the main benefit of luminance masking within CSS masking layers is that you can use existing image files, and that it is consistent with what designers expect.  As Dirk said, mask layers in GIMP and Photoshop and probably other tools use white/black mask layers.  However, those tools don't yet export to CSS syntax (since there isn't the browser support).  They either export to SVG masks or to semi-transparent PNG images that have the mask and image layers already composited together.

**Comment by dirkschulze** [comment]
@jrmuizel All those tools, no matter of the author, usually target vector content (SVG) and not HTML content. For SVG, luminance masks are widely supported but alpha masking is not (the opposite to HTML).

**Comment by dirkschulze** [comment]
Closing the issue since there hasn't been any activity. Feel free to reopen if this still is relevant.
