### ISSUE TITLE
[filter-effectss-1] All color values/formulas either between 0..1 or 0..255

### ISSUE THREAD

**Issue by dirkschulze** [w3c/fxtf-drafts#192]
Imported from https://www.w3.org/Bugs/Public/show_bug.cgi?id=22950

> Make sure that the spec is consistent with color ranges. They should either be all between 0..1 or 0..255.

**Comment by AmeliaBR** [comment]
Some filter primitives require normalization of colors (to 0-1), some can operate on normalized colors or device-dependent colors so long as RGBA are fully decomposed, while others can operate on any color space, including alpha-premultiplied colors (because they don't actually change color values).

So I don't think "consistent" is a reasonable goal.  However, I would say that the spec should probably be clearer about when color normalization is required.
