### ISSUE TITLE
[motion-1] Direction of offset-rotate at segment boundaries

### ISSUE THREAD

**Issue by karip** [w3c/fxtf-drafts#209]
The direction at segment boundaries used by [offset-rotate](https://drafts.fxtf.org/motion-1/#offset-rotate-property) came up during discussion about the SVG [`pathAngleAtLength()`](https://github.com/w3c/svgwg/issues/338) function. I’m opening this issue to get more feedback.

The direction at segment boundaries can be either the direction of the previous path segment or the direction of the next path segment.

Animation software seems to use either of them. After Effects seems to use the direction of the previous path segment. Apple Motion seems to use the direction of the next path segment.

CSS Motion Path defines the direction to be the direction of the previous path segment and Google Chrome has implemented it that way.

Should it be changed to be the direction of the next path segment?

[SVG 2 Path Directionality](https://svgwg.org/svg2-draft/paths.html#PathDirectionality) defines __the direction at the start of a path segment__ and __the direction at the end of a path segment__. CSS Motion Path could be changed to reference either of them to get a more precise definition which covers also zero-length subpaths.

**Comment by ewilligers** [comment]
SVG markers, animateMotion, CSS Motion Path and 'b' path commands should all use consistent direction.

Ideally, the SVG spec would normatively describe direction, and the motion path spec would link.

An SVG pathAngleAtLength() function would be excellent. Other specs could link to that instead of [‘path’ element implementation notes](https://www.w3.org/TR/SVG/implnote.html#PathElementImplementationNotes) (the most precise definition of direction in SVG 1.1). Web platform tests should cover 0 length paths like 'm 100 100 b -90'.

(I'm responsible for the Blink motion path implementation. I simply reused the internal function [PointAndNormalAtLength](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/graphics/Path.h?type=cs&q=PointAndNormalAtLength&l=93) used by animateMotion. Any bugs in that method should not be baked into the motion path spec.)

**Comment by heycam** [comment]
The [SVG 2 Path directionality](https://svgwg.org/svg2-draft/paths.html#PathDirectionality) section says:

> Otherwise, if the given distance along the path occurs at a path segment boundary, then the direction of the path is the direction at the start of the segment at the given distance, considering each segment to be endpoint exclusive.

So I think we should follow that.
