### ISSUE TITLE
[filter-effects] Allow intermediate negative colour values

### ISSUE THREAD

**Issue by ConradIrwin** [w3c/fxtf-drafts#221]
ref. https://www.w3.org/TR/SVG11/filters.html#feColorMatrixElement

I'm trying to invert the colour of a page (white background -> black background) but preserve the color of images. A naive solution is to do this:

```
body {
  filter: invert(1) hue-rotate(180deg);
}
img {
  filter: hue-rotate(180deg) invert(1);
}
```

But this doesn't quite work because the channel outputs of the first hue-rotate is truncated to [0..255], this causes the two hue-rotates (which should be a no-op) to lose information.

**Comment by dirkschulze** [comment]
@ConradIrwin That is correct, because of the truncation you'll loose information. Also, hue-rotate is done in the RGB color space which is the main issue here. For compatibility reasons this can not be changed anymore.

**Comment by AmeliaBR** [comment]
Some filter effects rely on the fact that values are clamped after each operation.

It is harder to create out-of-range channel values with the shorthand filters than with SVG filters, but you can still do it. The `contrast` filter is the only one that can create negative out-of-range values.  What you're actually seeing with `hue-rotate` is too-high out-of-range values (greater than 255 when converted to RGB).  Blown-out highlights like that can also be created with `brightness` and `sepia` filters.

Here's an example of a filter effect that relies on `contrast()` values getting clamped:

https://codepen.io/AmeliaBR/pen/zpJwYX?editors=0100

The real issue with the code @ConradIrwin posts is that the `hue-rotate()` filter is designed to preserve luminance while changing hue, and different hues have different potential luminance ranges within the RGB gamut. So when you rotate from a bright green to a blue hue, there is no way for blue to be as bright (by luminance measure) as the green was.

The preserve-luminance adjustments are confusing in other situations, like trying to use `hue-rotate` to match an `hsl()` color (`hsl()` uses "lightness", not "luminance", treating the RGB channels equally; it's gamut directly matches the RGB gamut).

Ideally, there would be an extra parameter to `hue-rotate` to switch it to preserve "lightness" instead of "luminance":

```css
filter: hue-rotate(180deg lightness)
```

Since this would a new feature, instead of a change to default behavior, it could be added in a future level of the spec if there is sufficient interest.

**Comment by ConradIrwin** [comment]
@amiliabr, thanks for the simple explanation! I'd love to have a hue-rotate that preserves lightness (or is invertible in some way).

**Comment by svgeesus** [comment]
> Some filter effects rely on the fact that values are clamped after each operation.

Yes. One way past this would be to use CSS4 Color Working Colorspace, whose initial value will be sRGB. Switching to another colorspace would mean that the computed colors are no longer out of gamut and thus, not clamped. Lab would be one example.

**Comment by AmeliaBR** [comment]
@svgeesus 
That's a good point. Maybe the wording could be changed to say that values are clamped to the gamut of the working color space after each operation, rather than specifying particular channel values for clamping.

But that can probably wait until a future version of the spec, once the [working color space](https://drafts.csswg.org/css-color-4/#working-color-space) syntax and behavior has been figured out.

**Comment by svgeesus** [comment]
> But that can probably wait until a future version of the spec

Yes.

**Comment by smfr** [comment]
I don't think we can allow negative color values here; that would require the UA to store unclipped sRGB in all the intermediate buffers (including composting code paths in other graphics libraries on the system). This isn't realistic until all OSes have some kind of deep color support.

**Comment by svgeesus** [comment]
>  until all OSes have some kind of deep color support.

Right. Which they don't now, but that is the direction they are all headed.

**Comment by dirkschulze** [comment]
To summarize: We agree that we will need CSS Color to proceed and define "working colorspace", either have a new filter function or extend `hue-rotate()` with a keyword but defer the definition of the new filter function or keyword and the decision about either one to a future version of the specification. If there is no objection I'd like to close this issue as deferred.
