### ISSUE TITLE
[motion-1] Computed value of offset-distance is vague

### ISSUE THREAD

**Issue by xidachen** [w3c/fxtf-drafts#365]
https://drafts.fxtf.org/motion-1/#offset-distance-property

The spec for offset-distance is:
For &lt;length&gt; the absolute value, otherwise a percentage.

Two questions here,
1. Why not resolve the percentage?
2. When interpolate 10px to 100% 0, Chrome gives 10px, Firefox gives calc(0% + 10px), which one is right?

**Comment by xidachen** [comment]
@stephenmcgruer

**Comment by stephenmcgruer** [comment]
To expand slightly: the value of offset-distance is specified as [<length-percentage>](https://drafts.csswg.org/css-values-4/#typedef-length-percentage), similar to properties such as `width`, but it's computed value is specified in a unique manner (as xidachen noted above):

`For <length> the absolute value, otherwise a percentage.`

This does not specify what to do for `calc(..)` values (as far as I know), and as such different browsers have chosen different behaviors. This is not related to interpolation, it can be seen with the simple example of:

```
<style>
#foo {
  offset-distance: calc(0% + 10px);
}
</style>
<div id='foo'></div>
<div id='writer'></div>
<script>
writer.innerText = 'The computed offset-distance for foo is: ' + getComputedStyle(foo).offsetDistance;
</script>
```

In Chrome this produces `10px`. In Firefox this produces `calc(0% + 10px)`.

The additional side-question that xidachen listed above is "why is it important that the percentages are not resolved?" The spec does not make it clear.

**Comment by flackr** [comment]
I suspect this behavior is because percentages are resolved relative to the length of the offset path rather than the box size. Have you tested that a percentage within a calc resolves against the path length and not the box size?

**Comment by stephenmcgruer** [comment]
Yes, that would make sense, but would also be good for the spec to explain (in a note).

In terms of testing, looks like none of the tests in `wpt/css/motion` actually test the effect of a percentage-containing-calc for `offset-distance` - https://wpt.fyi/results/css/motion?label=master&label=experimental

The `offset-distance-00x.html` tests all use percentages, and `offset-supports-calc.html` just checks getComputedStyle which doesn't actually tell you how it resolved.

So yes, some more tests would also be good there to verify browsers are actually computing the right thing, but this issue is looking to answer the question of "what is the correct computed style for `offset-distance: calc(0% + 10px)`?"

**Comment by stephenmcgruer** [comment]
Ahah, I think I just found it: https://drafts.csswg.org/css-values-3/#calc-computed-value

```Where percentages are not resolved at computed-value time, they are not resolved in calc() expressions, e.g. calc(100% - 100% + 1em) resolves to calc(1em + 0%), not to 1em. If there are special rules for computing percentages in a value (e.g. the height property), they apply whenever a calc() expression contains percentages.```

So I think Chrome is wrong here, and the correct behavior is already spec'd as `calc(0% + 10px)`

**Comment by stephenmcgruer** [comment]
Chrome bug has been opened - https://crbug.com/996240 , and I don't think there's anything left to discuss here.

**Comment by ewilligers** [comment]
I don't think the computed value spec sentence "For <length> the absolute value, otherwise a percentage." is what it should be, we should simply have similar wording to other `<length-percentage>` properties, e.g. "a computed `<length-percentage>` value"

The specific Chrome bug about calc(0% + 10px) isn't specific to this property.

The custom behavior for offset-distance (e.g. wrap around if we have a closed path) occurs when using the value.
