### ISSUE TITLE
[filter-effects-1] Is WPT test for accumulate correct?

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/fxtf-drafts#371]
I am currently working on implementing 'accumulate' composite support for filter in Chromium, and am having trouble resolving what I am reading in the spec and the associated WPT test.

From the spec, it appears that accumulation is just equivalent to replace (https://drafts.fxtf.org/filter-effects-1/#accumulation):

`Given two filter values Va and Vb, returns the filter value, Vb.`

Is that a correct reading? The WPT test (and Firefox's implementation) appears to combine the values via addition - https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/web-animations/animation-model/animation-types/property-types.js#L2245. It expects that:

`accumulate(blur(10px) brightness(0.3), blur(20px) brightness(0.1)) == blur(30px) brightness(0)`

With the justification that:

```
// brightness(0.1) onto brightness(0.3) means
// brightness((0.1 - 1.0) + (0.3 - 1.0) + 1.0). The result of this formula
// is brightness(-0.6) that means brightness(0.0).
```

Neither the blur calculation (which looks like explicit addition) or the brightness behavior (which looks like some sort of interpolation?) appears correct if I am reading the spec correctly.

@birtles

**Comment by birtles** [comment]
> From the spec, it appears that accumulation is just equivalent to replace (https://drafts.fxtf.org/filter-effects-1/#accumulation):
> 
> `Given two filter values Va and Vb, returns the filter value, Vb.`

Yes, this appears to be wrong. I'm not sure where it comes from but perhaps it was just put there until we worked out how to spec this.

> Neither the blur calculation (which looks like explicit addition) or the brightness behavior (which looks like some sort of interpolation?) appears correct if I am reading the spec correctly.

Assuming the above definition is wrong, I think the blur calculation is expected (component-wise addition as typical for accumulation).

For the brightness component, it's based on `brightness(1)` being the zero value. (Or as the spec puts it, "The initial value for interpolation is 1"). Since accumulation is supposed to accumulate the delta from the zero value, the operation here is to take the delta of `-0.7`, add to `-0.9` (i.e. `-1.6`) then apply that delta to the zero value (i.e. `-0.6` which then gets clamped to `0`). I believe that's consistent with what we do for `scale()` for example and I think it's the intuitive result here (building on `brightness(0.1)` will quickly get you into complete darkness).

**Comment by stephenmcgruer** [comment]
FYI we landed behavior in Chromium to match the behavior described here and that Firefox seems to have (based on tests), but it would be great to get the spec updated.
