### ISSUE TITLE
[motion-1] Incorrect type definition link in <size>

### ISSUE THREAD

**Issue by pyoor** [w3c/fxtf-drafts#411]
The `ray()` definition syntax links to the `<size>` definition in css-images-3, however; it appears that ray only accepts a limited number of these arguments: `[ closest-side | closest-corner | farthest-side | farthest-corner | sides ]`

https://github.com/w3c/fxtf-drafts/blob/cb4c0bb766ccc4a6670c240107c934865389089c/motion-1/Overview.bs#L126

I'm not sure what the usual process is for name conflicts among types.  Should the `<size>` definition be replaced with a group defintion containing:
`[ closest-side | closest-corner | farthest-side | farthest-corner | sides ]`

Or are these types of naming conflicts allowed?  And if so, the link in the `ray()` function should be changed to https://drafts.fxtf.org/motion-1/#valdef-offsetpath-size

**Comment by SebastianZ** [comment]
I also don't know whether there is a clear note about name conflicts somewhere but there are already some conflicting definitions like for the `path()` function in [Motion 1](https://drafts.fxtf.org/motion-1/#offsetpath-pathfunc) vs. [Shapes 1](https://drafts.csswg.org/css-shapes-1/#funcdef-path) or the `element()` function (see https://github.com/w3c/csswg-drafts/issues/1981). (But function names are also different because they are exposed to authors in opposite to other data types.)

Disregarding the name conflict, the syntax inside the `ray()` function obviously means the definition of `<size>` in that specification and not the one of CSS Images 3.

The question here is, can and should both definitions be merged into one?

In any case, the linking should be fixed for now, so I'll create a PR for that.

Sebastian

**Comment by cdoublev** [comment]
> The question here is, can and should both definitions be merged into one?

In my opinion, they can and should be merged, with specific rules written in prose, because it prevents [automatic parsing of value definition](https://github.com/w3c/csswg-drafts/issues/2921).

`<path()>` would reference the definition of CSS Shapes from Motion and Motion would define that `<'fill-rule'>` is invalid.

`<size>` would be merged to 

- `closest-side | closest-corner | farthest-side | farthest-corner | sides | <length-percentage>`
- or `closest-side | closest-corner | farthest-side | farthest-corner | sides | <length> | <length-percentage>{2}`
- or `closest-side | closest-corner | farthest-side | farthest-corner | sides | <length [0,∞]> | <length-percentage [0,∞]>{2}`

Motion would define that `<length-percentage>` is invalid, and CSS Shapes would define that `<length [0,∞]>` only applies when `<basic-shape>` is `circle` and `<length-percentage [0,∞]>{2}` only applies when `<basic-shape>` is `ellipse`.

**Comment by tabatkins** [comment]
We should make a single-use production for ray() that has the right keywords.

(Naming conflicts in productions are *not* allowed, but they do show up. Happy to fix them when they're pointed out.)

**Comment by cdoublev** [comment]
This issue seems to be fixed by https://github.com/w3c/fxtf-drafts/commit/9147ed7ee426e3ba3745daa533281b4ee0052f3a.
