### ISSUE TITLE
[css-motion] handling of both offset-position and offset-anchor being auto should be defined clearly

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#46]
The current spec isn't very clear about what happens when both <code>[offset-position](https://drafts.fxtf.org/motion-1/#offset-position-property)</code> and <code>[offset-anchor](https://drafts.fxtf.org/motion-1/#offset-anchor-property)</code> are both <code>auto</code>.

While my understanding of <code>offset-position: auto</code> is essentially that it starts from the element's position as defined by other CSS specifications, it's not clear how to turn that into a <code>&lt;position></code> value that can also be used for <code>offset-anchor</code>.

In particular, it seems that computing a <code>&lt;position></code> value to represent the "current position" depends on the value of <code>offset-anchor</code>, since (if I understand the spec correctly) it has to find the position in the containing block of the point at the <code>offset-anchor</code> within the element.  I think if the element is the same size as its containing block, then then either all possible answers are correct (if the element has the same position as its containing block) or no possible answer is correct (if the element has a different position from its containing block).

I think a clearer processing model is needed here.

I think one possible solution to the ambiguous/unsolvable cases may be to say that if <code>offset-position</code> and <code>offset-anchor</code> are both <code>auto</code>, then <code>offset-anchor</code> is treated as <code>center</code> instead of using the value from <code>offset-position</code>.

**Comment by shans** [comment]
We want to change the meaning of offset-anchor: auto to be offset-anchor: center, as this is a more sensible default for both motion along a path and polar positioning.

This should resolve the issue you've brought up?

**Comment by ewilligers** [comment]
Perhaps the initial value of offset-anchor should be 'auto', with text that 'auto' means that 'center' is used as the anchor position, unless the offset-position is a <position> and offset-path is 'none': in that case offset-position is used as the offset-anchor.

"the element's position as defined by other CSS specifications" would never be used by offset-anchor.

**Comment by fantasai** [comment]
I like @ewilligers' suggestion, as it handles the offset-position use case as well.

**Comment by ewilligers** [comment]
Thanks fantasai.


One detail I hadn't noticed earlier is that the transform-origin doesn't always default to center:

https://drafts.csswg.org/css-transforms/#transform-origin-property
"The initial used value for SVG elements without associated CSS layout box is 0 0."

Chrome shipped using transform-origin before offset-anchor existed, and changing to center instead of the transform-origin 0 0  makes some existing motion path demos change behavior.



Would the following be reasonable?

The initial value of offset-anchor should be 'auto', with text that 'auto' means that **transform-origin** is used as the anchor position, unless the offset-position is a \<position\> and offset-path is 'none': in that case offset-position is used as the offset-anchor.
