### ISSUE TITLE
[motion] Should failed references be treated as `none` or as a `0deg` zero-length path?

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#65]
> A reference that fails to download, is not a reference to an SVG shape element element, or is non-existent is ignored. No path and no stacking context are created.

This creates a stacking context dependency on downloading. I'm not sure that's a good idea, so maybe it's better to treat failed references as 0deg 0px paths?

**Comment by jihyerish** [comment]
I think, [`clip-path`](https://drafts.fxtf.org/css-masking-1/#propdef-clip-path) or [`shape-outside` ](https://drafts.csswg.org/css-shapes/#propdef-shape-outside)is similar case for handling failed references.
Both of them aren't applied if the reference is not valid.
Like those properties, offset-path works as `none` is given in this case. 

I'm not sure which one is better between `none` and `ray(0deg)`.

**Comment by ewilligers** [comment]
I agree with fantasai regarding stacking context dependency.

We need a zero length path, e.g. path('m 0 0'), so offset-distance has no effect.

We also need to specify that the bearing of the empty path('m 0 0') is 90deg, to avoid rotation: 'auto' is equivalent to '0deg'.

ray(0deg) is not suitable, because
(a) offset-distance might not be 0.
(b) rotation 'auto' causes a -90deg rotation.

**Comment by jihyerish** [comment]
> ray(0deg) is not suitable, because
(a) offset-distance might not be 0.
(b) rotation 'auto' causes a -90deg rotation.

You made a good point.

On second thought, the way to dealing with failed references in offset-path should be different in clip-path or shape-outside.

Then, the changes like below are reasonable?
- Failed references is treated as 'path(M10 10)' instead of 'none'
- For the zero-length path, 'offset-rotation: auto' is same as 'offset-rotation: 90deg'

**Comment by ewilligers** [comment]
> Failed references is treated as 'path(M10 10)' instead of 'none'
> For the zero-length path, 'offset-rotation: auto' is same as 'offset-rotation: 90deg'

Almost. `path(M10 10)` has a translation of 10,10. I used `path("m 0 0")` in pull request #104 , so we have no translation.

`offset-rotation: 90deg` would force a rotation, when we don't want one. In the pull request I clarified that a path's direction relative to the positive x-axis is what gives the offset-rotate 'auto' rotation. This is consistent with the spec's examples, with SVG's animateMotion and markers, and with Chrome's shipped implementation of motion-rotation (now offset-rotate).

SVG's [F.5 ‘path’ element implementation notes](https://www.w3.org/TR/SVG11/implnote.html#PathElementImplementationNotes)
"Markers, directionality and zero-length path segments"
"... , set the directionality for the path segment's start and end points to align with the positive x-axis in user space."
