### ISSUE TITLE
[geometry] Why does DOMMatrix not skew or flip on the Z axis?

### ISSUE THREAD

**Issue by tabatkins** [w3c/fxtf-drafts#8]
*On Thu, May 26, 2016 at 11:19 PM, /#!/JoePea <trusktr@gmail.com> wrote:*
> DOMMatrix classes only skew on X and Y, but not Z. Why not?
>
> (I also noticed that CSSSkew in Houdini also ignores the Z axis).

**Comment by tabatkins** [comment]
Because CSS Transforms only define 2d skews.

That just moves the question, of course. ^_^

**Comment by trusktr** [comment]
> only define

As in the spec only defines? Okay, so let's add 3D.

It could be done currently by nesting elements and rotating an axis 90 deg on the child then skewing on the parent, but that's too much work.

**Comment by smfr** [comment]
Skews are nasty in general because with some angles the element extends an infinite distance on some axes. This would be ugly to deal with on the z axis.

**Comment by tabatkins** [comment]
Yeah, but that's not a new issue - you can skew it to infinite-length with a 2d skew and then rotate it to point in the z axis.

But still, this is a question for the CSS Transforms spec, not the Geometry spec that merely reflects what CSS Transforms defines.

**Comment by dmvaldman** [comment]
Also, in "real" 3D there are not just 3 ways to skew, but 6! A skew is defined by 2 axes, one axis translated in the direction of the other. So for 3d when we say SkewX, and SkewY, we really mean SkewXY and SkewYX. Then there is also SkewXZ, SkewYZ, SkewZX and SkewZX.

However for the four last ones, it only makes sense to skew in Z if what your skewing has depth. Since everything is really 2D in the browser, I'm guessing these serve no purpose for transforming a single DOM element. They could be used, however, to transform a group of DOM elements offset from each other in the z-direction.

**Comment by trusktr** [comment]
Hello Tab,

*/#!/*JoePea

On Tue, Oct 18, 2016 at 6:31 AM, David Valdman <notifications@github.com>
wrote:

> Also, in "real" 3D there are not just 3 ways to skew, but 6! A skew is
> defined by 2 axes, one axis translated in the direction of the other. So
> for 3d when we say SkewX, and SkewY, we really mean SkewXY and SkewYX. Then
> there is also SkewXZ, SkewYZ, SkewZX and SkewZX.
>
> However for the four last ones, it only makes sense to skew in Z if what
> your skewing has depth. Since everything is really 2D in the browser, I'm
> guessing these serve no purpose for transforming a single DOM element. They
> could be used, however, to transform a group of DOM elements offset from
> each other in the z-direction.
>
​Very true. Here are examples of 3D objects made with DOM nodes, where
skewing in any direction could make sense (f.e. a bouncy effect in any
direction):

https://trusktr.io/clobe
https://jsfiddle.net/trusktr/ymonmo70/15
​​
